// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3b5akNCs1JfhQgPkRCD_QZ0hW2klZZ2I',
    appId: '1:483545794550:web:aada5aebb9d5612a0569d7',
    messagingSenderId: '483545794550',
    projectId: 'talenthire-d86a1',
    authDomain: 'talenthire-d86a1.firebaseapp.com',
    storageBucket: 'talenthire-d86a1.firebasestorage.app',
    measurementId: 'G-KJNLD1FTW9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDsaZPQvKp_vMSBoSGjashJWqefdOOlmk',
    appId: '1:483545794550:android:a1e3da5733eb84c10569d7',
    messagingSenderId: '483545794550',
    projectId: 'talenthire-d86a1',
    storageBucket: 'talenthire-d86a1.firebasestorage.app',
    databaseURL: 'https://talenthire-d86a1-default-rtdb.asia-southeast1.firebasedatabase.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKBVzGBJpaNSDokTVPqGFwy__KpOQ8R0s',
    appId: '1:483545794550:ios:1c730e825ac6a94e0569d7',
    messagingSenderId: '483545794550',
    projectId: 'talenthire-d86a1',
    storageBucket: 'talenthire-d86a1.firebasestorage.app',
    iosClientId: '483545794550-ob6hj33khbk0ekg3ouj1cmiiq782moa2.apps.googleusercontent.com',
    iosBundleId: 'com.talenthire.app',
    databaseURL: 'https://talenthire-d86a1-default-rtdb.asia-southeast1.firebasedatabase.app',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKBVzGBJpaNSDokTVPqGFwy__KpOQ8R0s',
    appId: '1:483545794550:ios:3be17e63d2d632c80569d7',
    messagingSenderId: '483545794550',
    projectId: 'talenthire-d86a1',
    storageBucket: 'talenthire-d86a1.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3b5akNCs1JfhQgPkRCD_QZ0hW2klZZ2I',
    appId: '1:483545794550:web:6cff691c0314ca100569d7',
    messagingSenderId: '483545794550',
    projectId: 'talenthire-d86a1',
    authDomain: 'talenthire-d86a1.firebaseapp.com',
    storageBucket: 'talenthire-d86a1.firebasestorage.app',
    measurementId: 'G-KQ0DZW0D86',
  );
}
